# -*- coding: utf-8 -*-
"""Example 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iUuhTZwcqisQeqBWuWpFpNSFGL8hd_yi
"""

temp_c = float(input('Nhập nhiệt độ theo độ C: '))
temp_f = ((9/5)*temp_c + 32)
print('Nhiệt độ theo độ F: ',temp_f)