# -*- coding: utf-8 -*-
"""Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/148aL8P0QRa3QvcR8bPa2XlugRtvwyPOg

# Print(Parameter)
"""

number_of_days =  10
print(number_of_days)
distance = 20.5
print(distance)
greeting = "Hello AI-Viet-Nam"
print(greeting)
is_student = True
print(is_student)

"""# Type(Parameter)"""

number_of_days =  10
data_type_of_number = type(number_of_days)
print(data_type_of_number)
distance = 20.5
data_type_of_distance = type(distance)
print(data_type_of_distance)
greeting = "Hello AI-Viet-Nam"
data_type_of_greeting = type(greeting)
print(data_type_of_greeting)
is_student = True
data_type_of_is_student = type(is_student)
print(data_type_of_is_student)

"""# Input(Promt)"""

input_data = input("Hãy nhập tên của bạn!")
data_type_input_data = type(input_data)
print("-------------------------------------")
print(data_type_input_data)
print(input_data)

"""# Type Conversion"""

input_data = input("Hãy nhập tuổi của bạn!")
input_data_int = int(input_data)
data_type = type(input_data_int)
print("-------------------------------------")
print(data_type)
print(input_data_int)