# -*- coding: utf-8 -*-
"""Function_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RR2fpHc9Bvrwm_BMabnuEaU0Rrs3PRW4

# Math Module
"""

# absolute value of x
import math
n1 =  1
n2 = -2
print(math.fabs(n1))
print(math.fabs(n2))

# log (x)
import math
x = 4
print(math.log(x))
print(math.log(math.e))

# Tính Sin, Cosin
import math
x = 2
print('sin(x) = ',math.sin(x))
print('cos(x) = ',math.cos(x))

# Một số dạng khác
import math
print(math.e)
print(math.pi)
x = 4
print('exponential of x = ',math.exp(x))
print('square root of x = ',math.sqrt(x))